### ISSUE TITLE
Installation error when crossmod LCA.d fails to compile

### ISSUE THREAD

**Issue by PixelsnPolygons** [dark0dave/BaeBG2#14]
I keep getting an installation error due to the LCA crossmod banter support. The LCA.d file fails to compile (both v0.0.3 and v0.0.2), but I couldn't determine the problem in the dialogue chain.

I had to comment out the LCA detection block from the TP2 to get BaeBG2 to install, but I would prefer including the LCA crossmod banter.

**Comment by dark0dave** [comment]
I'll take a look!

**Comment by dark0dave** [comment]
@PixelsnPolygons  I've separated out the crossmod component. And made some changes to it. I will do a new release so you can try it.
