### ISSUE TITLE
Duplicate Baeloth choices in fate spirit

### ISSUE THREAD

**Issue by ch10ke** [dark0dave/BaeBG2#26]
Hello I'd like to report that with the recent version there are two Baeloth choices in the fate spirit summon dialog.

**Comment by dark0dave** [comment]
Hi @ch10ke yes, I have squashed that one!

**Comment by dark0dave** [comment]
Thank you for the report, I will release a new version shortly

**Comment by dark0dave** [comment]
@ch10ke if you could give https://github.com/dark0dave/BaeBG2/releases/tag/v0.0.8 a try please.
![image](https://github.com/user-attachments/assets/a4595542-f31f-4ec6-9691-2a149a4a0bfe)
